<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageVersion Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageVersion Include="FluentAssertions" Version="8.6.0" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageVersion Include="Hashids.net" Version="1.7.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.9" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.10" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.7.2" />
    <PackageVersion Include="Scrutor" Version="6.1.0" />
    <PackageVersion Include="Serilog" Version="4.3.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageVersion Include="Serilog.Sinks.Seq" Version="9.0.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="9.0.4" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="6.0.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
</Project>