<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Hashids.net" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="Serilog" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UrlShortener.Domain\UrlShortener.Domain.csproj" />
    <ProjectReference Include="..\UrlShortener.SharedKernel\UrlShortener.SharedKernel.csproj" />
  </ItemGroup>
</Project>
