<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Hashids.net" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="Serilog" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UrlShortener.SharedKernel\UrlShortener.SharedKernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="UseCases\" />
    <Folder Include="UseCases\Shorteners\" />
  </ItemGroup>
</Project>
